# Generated by Django 5.1.5 on 2025-02-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('user_agent', models.TextField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_data', models.JSONField(null=True)),
                ('response_data', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
